### PR TITLE
Support I3C for S32Z27

### PR DESCRIPTION
**Pull request by Dat-NguyenDuy**
This adds glue code to reuse i3c mcux sdk for s32z27. Alsoa dd patch on the mcux driver for fixing compiler warnings

### CODE REVIEW

**Comment by mmahadevan108** [comment]
Has this change be submitted to the MCU_SDK github?

**Comment by manuargue** [comment]
> Has this change be submitted to the MCU_SDK github?

Right, @Dat-NguyenDuy it should be submitted so we can remove the patch in next SDK update. And also is missing a Zephyr pr enabling I3C on S32Z?

**Comment by Dat-NguyenDuy** [comment]
> Has this change be submitted to the MCU_SDK github?

I opened PR in mcux-sdk https://github.com/nxp-mcuxpresso/mcux-sdk/pull/149

**Comment by mmahadevan108** [comment]
@manuargue , do these changes look fine to you?

**Review by manuargue — APPROVED** [review]

**Pull request merged**
