### PR TITLE
NXP HAL: remove all binary blobs for power management libraries

### PR DESCRIPTION
**Pull request by yvanderv**
These binary blobs are not necessary.

The list of blobs was established with:

$ find [A-Za-z0-9]* -type f | egrep -e '\.a$' | grep libpower

The removal was executed with

$ find [A-Za-z0-9]* -type f | egrep -e '\.a$' | grep libpower | xargs -n1 git rm

Signed-off-by: Yves Vandervennet <yves.vandervennet@nxp.com>

### CODE REVIEW

**Comment by dleach02** [comment]
@yvanderv can you add a separate commit to this to remove the FLM files as well

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
I leave it to @dleach02 but this might be a change to get into the release.

**Review by danieldegrasse — APPROVED** [review]

**Comment by yvanderv** [comment]
We're missing one review here. David, whenever you have a chance.

**Comment by jahedul-haque** [comment]
Please add a LICENSE File to the hal_nxp repository, it is very difficult to use zephyr with NXP devices without the License file.

**Comment by mmahadevan108** [comment]
@jahedul-haque, thanks for your comment. I am checking with the NXP team about your suugestion.

**Comment by DerekSnell** [comment]
> Please add a LICENSE File to the hal_nxp repository, it is very difficult to use zephyr with NXP devices without the License file.

Hi @jahedul-haque ,
Thank you for raising this.  We created a new issue https://github.com/zephyrproject-rtos/zephyr/issues/61514 to track this, and NXP will be updating the HAL soon with a license file.

For future reference, when using GitHub with Zephyr, to make improvement requests like this, it is better to create a new, single Issue, instead of adding comments to multiple unrelated PRs, some of which have merged already.

Thanks again

**Pull request merged**
