### PR TITLE
bump usb middleware to mcux v2.14.0

### PR DESCRIPTION
**Pull request by jsiverskog**

### CODE REVIEW

**Comment by jsiverskog** [comment]
corresponding zephyr pr: https://github.com/zephyrproject-rtos/zephyr/pull/67483

**Comment by jsiverskog** [comment]
@danieldegrasse : do you have time to review this? thanks

**Comment by jsiverskog** [comment]
@danieldegrasse : what do i have to do in order for this to get merged?

**Comment by danieldegrasse** [comment]
> @danieldegrasse : what do i have to do in order for this to get merged?

Let's get the PR on the Zephyr side approved. Once @hakehuang approves that PR, I think we are good to merge this, and move forwards. @mmahadevan108, do you agree with this approach?

**Comment by dleach02** [comment]
I also have pulled in these files into my  SDK 2.15.000 PR. We had a build issue that is being looked.

**Comment by danieldegrasse** [comment]
@jsiverskog can you rebase to resolve conflicts?

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
