### PR TITLE
devices: MIMX8QM6 / MIMX8QX6: add support for IRQ_STEER driver

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Depends on: https://github.com/nxp-mcuxpresso/mcux-sdk/pull/169

### CODE REVIEW

**Comment by LaurentiuM1234** [comment]
dependency merged, good to go

**Review by iuliana-prodan — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@mmahadevan108 @dleach02  good to be merged.

**Comment by dbaluta** [comment]
This can be closed. Updates are contained in @dleach02  bigger PR: https://github.com/zephyrproject-rtos/hal_nxp/pull/329

**Comment by LaurentiuM1234** [comment]
Closing. Changes should be in https://github.com/zephyrproject-rtos/hal_nxp/pull/329

**Pull request closed without merging**
