### PR TITLE
mcux: components: Added global Zephyr FSL OSA port

### PR DESCRIPTION
**Pull request by Radimli**
Extended version of FSL OSA Zephyr port, using static allocation.

### CODE REVIEW

**Comment by Radimli** [comment]
Already upstreamed in mcux-sdk.

**Review by mmahadevan108 — APPROVED** [review]

**Review by decsny — APPROVED** [review]

**Comment by dleach02** [comment]
this should have been associated with a Zephyr side PR to update the manifest... going to be challenging to get this merged given the merge window tomorrow

**Comment by mmahadevan108** [comment]
I have created the Zephyr side PR to pull this change into Zephyr.

**Review by danieldegrasse — CHANGES_REQUESTED** [review]
It looks like the OSA update may cause some CI failures: https://github.com/zephyrproject-rtos/zephyr/runs/26200649050. Please feel free to dismiss my block if these are not related, or if we fix the issue. For the time being though, I think we should take another look to make sure that these changes won't break CI

**Comment by MarkWangChinese** [comment]
Do we need to remove [modules/hal_nxp/fsl_os_abstraction.h](https://github.com/zephyrproject-rtos/zephyr/blob/main/modules/hal_nxp/fsl_os_abstraction.h)?

**Pull request closed without merging**
