### PR TITLE
imx93: update pinctrl dtsi

### PR DESCRIPTION
**Pull request by CkovMk**

### CODE REVIEW

**Comment by JiafeiPan** [comment]
Some high level comments: 
1) 2.14.0 update will be integrated by https://github.com/zephyrproject-rtos/hal_nxp/pull/270, so remove related update. 
2) Don't includes internal information or link in patch commit information.
3) try to upstream a small set of patch in order to make review easier.

**Comment by CkovMk** [comment]
@JiafeiPan 
I've rebased the commits onto [SDK2.14](https://github.com/zephyrproject-rtos/hal_nxp/pull/270). Is it ok?

**Comment by mmahadevan108** [comment]
@CkovMk Please split this into 2 separate PR's.
1. For the pintctrl changes
2. For pulling in `fsl_rgpio` driver. This should have an associated Zephyr PR as well.

You could update this PR to have only pinctrl changes and open a separate PR for `fsl_rgpio`

**Comment by CkovMk** [comment]
Hi @mmahadevan108 , updated this pr for pinctrl only.

For rgpio driver, a new pr is created: https://github.com/zephyrproject-rtos/hal_nxp/pull/278 . zephyr driver is https://github.com/zephyrproject-rtos/zephyr/pull/62622

**Comment by CkovMk** [comment]
@mmahadevan108 zephyr pr for pinctrl changes: https://github.com/zephyrproject-rtos/zephyr/pull/62755
thx

**Comment by mmahadevan108** [comment]
@CkovMk, kindly remove the mcux changes in this PR and keep the files changes limited to ones you wish to add/modify. This will make reviewing easier.

**Comment by CkovMk** [comment]
@mmahadevan108  
Done. Thanks

**Review by danieldegrasse — APPROVED** [review]

**Comment by JiafeiPan** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/62755 and this PR depends on each other, so need to merge them simultaneously after both are approved.

**Comment by mmahadevan108** [comment]
Please resubmit this PR. We had to revert this as it was causing failures on the Zephyr side since the Zephyr PR is still not ready.

**Comment by CkovMk** [comment]
resubmitted as #289 
Thanks

**Pull request merged**
