### PR TITLE
dts: add pinctrl dts header files for LPC55S36

### PR DESCRIPTION
**Pull request by NeilChen93**
add pin control dts header files with pinmux options for LPC55S36

Signed-off-by: Neil Chen <cheng.chen_1@nxp.com>

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@NeilChen93 Can you please share the steps followed to generate these files.

**Comment by NeilChen93** [comment]
image

**Comment by NeilChen93** [comment]
@mmahadevan108 , I asked Daniel by email before how to generate the pinctrl files. The python script files I used are in https://github.com/zephyrproject-rtos/hal_nxp/pull/159/commits. And the pin control header are generated by script "python ./mcux/scripts/lpc_gen_headers.py –-copyright {PATH_TO_PROCESSOR_ROOT}", On my machine, the PATH_TO_PROCESSOR_ROOT is C:\ProgramData\NXP\mcu_data_v11\processors\LPC55S36.

**Review by danieldegrasse — APPROVED** [review]
Files look correctly generated to me. LGTM.

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
