### PR TITLE
mcux: Add support for LPC55S28

### PR DESCRIPTION
**Pull request by chrta**
Add MCUXpresso SDK version 2.8.2 (2020-11-09) for LPC55S28
SoCs. This is the latest version available for these SoCs.

Origin: MCUXpresso SDK
License: BSD 3-Clause
URL: mcux.nxp.com
Maintained-by: External

Signed-off-by: Christian Taedcke <christian.taedcke@lemonbeat.com>

### CODE REVIEW

**Comment by chrta** [comment]
Pull request in zephyr repo to add support for LPC55S28-EVK will follow soon

**Review by mmahadevan108 — APPROVED** [review]

**Review by galak — APPROVED** [review]

**Review by agansari — CHANGES_REQUESTED** [review]
@chrta this looks good, but have you used hal\nxp\mcux\scripts\import_mcux_sdk.py to import the necessary files ?

**Comment by chrta** [comment]
> @chrta this looks good, but have you used hal\nxp\mcux\scripts\import_mcux_sdk.py to import the necessary files ?

Yes, i have used that script. There was one minor change i omitted of another file outside of the mcux/devices dir. As far as i remember only some line break. Should i recheck?

**Review by agansari — APPROVED** [review]
LGTM

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
