### PR TITLE
MXRT600 Add OS Timer

### PR DESCRIPTION
**Pull request by mmahadevan108**

### CODE REVIEW

**Review by galak — COMMENTED** [review]
Where is SystemCoreClock used?

**Comment by mmahadevan108** [comment]
https://github.com/NXPmicro/zephyr/blob/Update_MXRT600_Timer/arch/arm/core/aarch32/cortex_m/timing.c#L38

I am working to switch RT600 to use a different timer instead of SYSTICK. This is done so we can start implementing SoC power management states on NXP platforms. Eventually this will grow to other NXP SoC's as well, hence this change.

**Comment by mmahadevan108** [comment]
I have changed the PR to add system.c file only for RT600.

**Review by galak — APPROVED** [review]

**Comment by galak** [comment]
At some point we should see if we define `SystemCoreClock` based on devicetree in the future.

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
