### PR TITLE
devices: MIMX8UD7: add EDMA rev2 support

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Patch has already been merged to MCUX-SDK via https://github.com/nxp-mcuxpresso/mcux-sdk/pull/181.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
Please fix merge conflict

**Comment by LaurentiuM1234** [comment]
Rebased

**Comment by mmahadevan108** [comment]
Is there a Zephyr side PR that pulls this change?

**Comment by LaurentiuM1234** [comment]
> Is there a Zephyr side PR that pulls this change?

Will submit after https://github.com/zephyrproject-rtos/zephyr/pull/71257 gets merged

**Review by dbaluta — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
