### PR TITLE
mcux: Add PHY_OMS_FACTORY_MODE_MASK definition for KSZ8081 PHY

### PR DESCRIPTION
**Pull request by armandciejak**
Used by https://github.com/zephyrproject-rtos/zephyr/pull/23413/files

### CODE REVIEW

**Comment by armandciejak** [comment]
Could someone take care of that PR?

**Comment by armandciejak** [comment]
@agansari can you take care of that PR?

**Comment by agansari** [comment]
@armandciejak please reference this PR to your other PR that uses factory reset in the description.

**Comment by armandciejak** [comment]
> Please use a real email in your `Signed-off-by`

Is it an official policy? I've used that email for all my commit in Zephyr and it was not a problem so far.

**Comment by MaureenHelm** [comment]
> > Please use a real email in your `Signed-off-by`
> 
> @MaureenHelm Is it an official policy? I've used that email for all my commits in Zephyr and so far it was not a problem.

Perhaps it was missed. I would still like to see this fixed.

**Comment by pfalcon** [comment]
> Please use a real email in your Signed-off-by

@nashif: Perhaps makes sense to tighten up email address check to exclude @users.noreply.github.com .

**Comment by armandciejak** [comment]
> > > Please use a real email in your `Signed-off-by`
> > 
> > 
> > @MaureenHelm Is it an official policy? I've used that email for all my commits in Zephyr and so far it was not a problem.
> 
> Perhaps it was missed. I would still like to see this fixed.

Thanks for your answer, I'll check our company policy before fixing this.

**Comment by armandciejak** [comment]
@MaureenHelm I changed my email in the signed-off-by.

**Pull request merged**
