### PR TITLE
hal: nxp: mcux: Add device and driver files for i.MX8M Plus SoCs

### PR DESCRIPTION
**Pull request by trowbridgec-laird**
Add device and driver files for i.MX8M Plus SoCs based on MCUXpresso SDK 2.10.0 (MIMX8ML8_cm7).

Note: this is my first time adding a PR for this project, so please let me know if I'm missing anything!

### CODE REVIEW

**Review by mmahadevan108 — CHANGES_REQUESTED** [review]
@trowbridgec-laird . This PR is missing changes to `mcux/CMakeLists.txt` file. This is needed to pull in the files from the `devices` folder.
Also, please take a look at PR https://github.com/zephyrproject-rtos/hal_nxp/pull/123. We should be getting all the files you need as part of this PR.

**Comment by trowbridgec-laird** [comment]
@mmahadevan108 I think that the necessary files from the `devices` folder are pulled in with the last `else()` in the first `if/else` statement of that file:
```cmake

if("${MCUX_DEVICE}" STREQUAL "LPC54114")
...
else()
  set(MCUX_CPU CPU_${CONFIG_SOC_PART_NUMBER})
endif()
```

But based on the changes coming with PR #123, is this PR even needed at all now?

**Comment by trowbridgec-laird** [comment]
@mmahadevan108 I pulled in the branch from PR #123 and was able build the sample project with my from PR https://github.com/zephyrproject-rtos/zephyr/pull/40293 after removing the code related to `AUDIOMIX`.

As that peripheral isn't necessary for basic board support, I might remove it from the PR.

**Comment by mmahadevan108** [comment]
I will update  PR #123 to include `AUDIOMIX `.

**Comment by mmahadevan108** [comment]
> @mmahadevan108 I pulled in the branch from PR #123 and was able build the sample project with my changes from PR [zephyrproject-rtos/zephyr#40293](https://github.com/zephyrproject-rtos/zephyr/pull/40293) after removing the code related to `AUDIOMIX`.
> 
> As that peripheral isn't necessary for basic board support, I might remove it from the PR.

I think this PR is not needed as we will get the support you are looking for once we move Zephyr HAL to use to `mcux-sdk` github

**Comment by trowbridgec-laird** [comment]
Sounds good! I'll close this PR and add a comment in my PR to the main Zephyr repo (https://github.com/zephyrproject-rtos/zephyr/pull/40293) to depend on PR #123 instead of this one.

**Pull request closed without merging**
