### PR TITLE
mcux: Enable inclusion of MCUX flexio and flexio_spi drivers

### PR DESCRIPTION
**Pull request by MikhailSiomin**
I'm developing **spi_mcux_flexio** driver. It requires **fsl_flexio.c** and **fsl_flexio_spi.c** drivers from **HAL**.
**CONFIG_MCUX_FLEXIO** will be defined at *zephyr\drivers\misc\Kconfig.mcux_flexio* file:
```
config MCUX_FLEXIO
	bool
	depends on HAS_MCUX_FLEXIO
	depends on CLOCK_CONTROL
	help
	  Enable the FlexIO for SPI instances.
	  FlexIO is not used separately.
```
**CONFIG_SPI_MCUX_FLEXIO** will be defined at *zephyr\drivers\spi\Kconfig.mcux_flexio* file:
```
config SPI_MCUX_FLEXIO
	bool "MCUX FlexIO SPI driver"
	depends on HAS_MCUX_FLEXIO
	depends on CLOCK_CONTROL
	select MCUX_FLEXIO
	help
	  Enable support for MCUX FlexIO SPI driver.
```

Signed-off-by: Mikhail Siomin <victorovich.01@mail.ru>

### CODE REVIEW

**Comment by henrikbrixandersen** [comment]
I'd be interested to see your Zephyr FlexIO driver implementation. I have a solution downstream, which defines a generic FlexIO driver managing the FlexIO resources allowing child drivers to request resources (timers, shared IRQ, shift registers, ...).

**Comment by MikhailSiomin** [comment]
My driver implementation is simple. You can see it here https://github.com/MikhailSiomin/zephyr/tree/mcux_flexio_spi

**Comment by MikhailSiomin** [comment]
Open issue on this topic https://github.com/zephyrproject-rtos/zephyr/issues/52612

**Comment by MikhailSiomin** [comment]
I remade the FlexIO driver, taking your (@henrikbrixandersen) implementation as a basis. You can see it [here](https://github.com/MikhailSiomin/zephyr/tree/mcux_flexio).

**Comment by MikhailSiomin** [comment]
I understand that the implementation of the new driver takes a lot of time, but please add the ability to include dependent modules from hal. This would make it easier for us to use the driver in a separate branch. Thanks.

**Review by mmahadevan108 — APPROVED** [review]

**Pull request merged**
