### PR TITLE
mcux: add support of MK66F18

### PR DESCRIPTION
**Pull request by parthitce**
ext: hal: nxp: mcux: add device files for MK66F18

Add mcux SDK_2.7.0_MK66FN2M0xxx18 drivers and device
header files for MK66F18.

Origins: NXP MCUxpresso SDK 2.7.0
URL: mcuxpresso.nxp.com
Maintained-by: External

Signed-off-by: Parthiban Nallathambi <pn@denx.de>

### CODE REVIEW

**Comment by galak** [comment]
looks good, will pend approval for a SoC/Board support on the Zephyr tree side.

**Comment by parthitce** [comment]
@galak Thanks, I will push the support for K66F based [IP Switch Board](https://www.segger.com/evaluate-our-software/segger/embosip-switch-board/) now.

**Comment by parthitce** [comment]
@galak Can this be planned for next release? I have re-based the dependent PR and all checks are passed.

**Comment by galak** [comment]
> @galak Can this be planned for next release? I have re-based the dependent PR and all checks are passed.

Don't see any reason this shouldn't be able to get in for 2.3

**Comment by parthitce** [comment]
> please update `mcux/README`

@MaureenHelm Done, thanks.

**Pull request merged**
