### PR TITLE
middleware: wifi_nxp: update version to r50.z_up.p4

### PR DESCRIPTION
**Pull request by MaochenWang1**
mcux: components: Support RU TX power table
middleware: wifi_nxp: update version to r50.z_up.p4
mcux: hal_nxp: modify the sleep flag address between CPU2 and CPU3

### CODE REVIEW

**Comment by MaochenWang1** [comment]
Hi @dleach02 @danieldegrasse @decsny @mmahadevan108  please review this wifi_nxp update from downstream.

**Comment by MaochenWang1** [comment]
Hi @dleach02 @danieldegrasse @decsny @mmahadevan108 please review this wifi_nxp update from downstream.

**Review by danieldegrasse — APPROVED** [review]

**Comment by MaochenWang1** [comment]
Hi @dleach02 @decsny @mmahadevan108 please review this wifi_nxp update from downstream.

**Comment by MaochenWang1** [comment]
Hi @dleach02 @decsny @mmahadevan108 please review and merge this wifi_nxp update from downstream.

**Pull request merged**
