### PR TITLE
mcux: add support for SMARTDMA driver on MCXN947

### PR DESCRIPTION
**Pull request by danieldegrasse**
Add support for SMARTDMA driver on MCXN947. This requires two changes:
- include inputmux driver when SMARTDMA driver is enabled, as this driver is required to connect the SMARTDMA signals to gpios/interrupts
- patch MCUX SDK to properly include inputmux connections header for MCXN947 device

### CODE REVIEW

**Review by mmahadevan108 — APPROVED** [review]

**Review by dleach02 — APPROVED** [review]

**Comment by dleach02** [comment]
can you address the merge conflict

**Comment by decsny** [comment]
Is this in upstream mcux-sdk

**Comment by danieldegrasse** [comment]
> Is this in upstream mcux-sdk

No, but a PR has been opened internally to add this to the SDK- so it should propagate into the upstream and enable us to drop this patch in the future

**Comment by dleach02** [comment]
@danieldegrasse is it safe to merge this PR so you can update your Zephyr side PR?

**Pull request merged**
