### PR TITLE
mcux: Import NXP SDK USB IP3511 controller driver.

### PR DESCRIPTION
**Pull request by MarkWangChinese**
Support LPC55S69 usb function

The codes are based on MCUXpresso SDK 2.7.0
Put the driver files to mcux/middleware/usb/device.
Add driver files to CMakeLists.txt
Update usb_dc_mcux.h to contain the IP3511 driver.

Signed-off-by: Mark Wang <yichang.wang@nxp.com>

### CODE REVIEW

**Comment by MarkWangChinese** [comment]
Please reference the zephyr PR https://github.com/zephyrproject-rtos/zephyr/pull/19014

**Comment by MarkWangChinese** [comment]
Hi @MaureenHelm , the zephyrproject-rtos/zephyr#19014 seems approved, could you please check this PR?

**Comment by MarkWangChinese** [comment]
> What version of the MCUXpresso SDK did this come from? Please document in the commit message.

Has added the version in the commit content.

**Comment by dleach02** [comment]
obsolete... support added in different PR

**Pull request closed without merging**
