### PR TITLE
cmake: Add ecspi driver to shared drivers

### PR DESCRIPTION
**Pull request by Fladdan**
Hi, to use the ECSPI driver in Zephyr it is mandatory to have it enabled in the hal_nxp repository.

### CODE REVIEW

**Comment by Fladdan** [comment]
Since nobody was assigned automatically to this PR and I can't select reviewers, I mention you directly: @dleach02 @danieldegrasse @mmahadevan108

**Comment by mmahadevan108** [comment]
@Fladdan , thank you for your PR. Is there a Zephyr PR associated with this change?

**Comment by Fladdan** [comment]
@mmahadevan108, there is no PR on the Zephyr side yet, since I first wanted to update this repo and then there could be an PR for Zephyr changing the revision of the hal_nxp and integrating the ECSPI driver.

**Comment by henrikbrixandersen** [comment]
> @mmahadevan108, there is no PR on the Zephyr side yet, since I first wanted to update this repo and then there could be an PR for Zephyr changing the revision of the hal_nxp and integrating the ECSPI driver.

Please see https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules for the process. You'll need to pull the changes from this PR into Zephyr in order to have a CI run confirming the changes.

**Comment by mmahadevan108** [comment]
Closing this PR as we have another one in review https://github.com/zephyrproject-rtos/hal_nxp/pull/339

**Pull request closed without merging**
