### PR TITLE
middleware: wifi_nxp: Fix build errors with latest hostapd

### PR DESCRIPTION
**Pull request by krish2718**
After hostap upmerge the signal data structure is moved.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
@krish2718 , do we need a Zephyr side PR to pull this change in?

**Comment by MaochenWang1** [comment]
Is it related to this change？
https://github.com/zephyrproject-rtos/hostap/pull/66

**Comment by krish2718** [comment]
> Is it related to this change？ [zephyrproject-rtos/hostap#66](https://github.com/zephyrproject-rtos/hostap/pull/66)

Yes, I will push an update to that PR which updates manifest.

**Comment by danieldegrasse** [comment]
Sorry, I may be misunderstanding something here- should https://github.com/zephyrproject-rtos/zephyr/pull/81606 have a reference to this PR and the hostap PR in the west manifest changes?

**Comment by krish2718** [comment]
> Sorry, I may be misunderstanding something here- should [zephyrproject-rtos/zephyr#81606](https://github.com/zephyrproject-rtos/zephyr/pull/81606) have a reference to this PR and the hostap PR in the west manifest changes?

I have updated the PR with this repo manifest, but during rebase the hostap manifest update is lost, it's now fixed, thanks.

**Comment by dleach02** [comment]
@MaochenWang1

**Comment by dleach02** [comment]
Will wait on the Zephyr side PR to reach approval stage

**Comment by jukkar** [comment]
NXP folks, I would like to see your +1 to https://github.com/zephyrproject-rtos/zephyr/pull/81606 before merging the hostap https://github.com/zephyrproject-rtos/hostap/pull/66 upgrade, so please review.

**Review by MaochenWang1 — APPROVED** [review]

**Comment by krish2718** [comment]
Please merge, hostap PR is merged, so, I can do a single push to update manifests.

**Pull request merged**
