### PR TITLE
Update to SDK 2.8

### PR DESCRIPTION
**Pull request by mmahadevan108**
Ran a build test on all NXP MCUX platforms. There is an update required to IMX8M soc.c file due to some changes to the clock macros.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @MaureenHelm @agansari @hakehuang

**Comment by galak** [comment]
@mmahadevan108 need a PR on the Zephyr side to show we didn't break anything with all these HAL updates.

**Comment by galak** [comment]
@mmahadevan108 looks like the import of new drivers etc might need to be run through dos2unix.  Not sure how you are doing the import.

**Comment by mmahadevan108** [comment]
I did run dos2unix on the files. Do you see anything that I may have missed?

**Comment by mmahadevan108** [comment]
PR for update to https://github.com/zephyrproject-rtos/zephyr/pull/27990

**Comment by galak** [comment]
> I did run dos2unix on the files. Do you see anything that I may have missed?

I just ran it on `dos2unix mcux/drivers/kinetis/*` and get:

```
[galak@spiff hal_nxp]$ git show | diffstat 
 fsl_acmp.c                  | 1324 ++---
 fsl_acmp.h                  | 1072 ++--
 fsl_adc12.c                 |  926 +--
 fsl_adc12.h                 |  748 +--
 fsl_adc16.c                 |  988 ++--
 fsl_adc16.h                 | 1024 ++--
 fsl_aoi.c                   |  428 -
 fsl_aoi.h                   |  372 -
 fsl_cache.c                 | 1000 ++--
 fsl_cache.h                 |  680 +-
 fsl_cmp.c                   |  742 +--
 fsl_cmp.h                   |  642 +-
 fsl_cmt.c                   |  660 +-
 fsl_cmt.h                   |  756 +--
 fsl_common.c                |  560 +-
 fsl_common.h                | 1344 ++---
 fsl_crc.c                   |  644 +-
 fsl_crc.h                   |  346 -
 fsl_dac.c                   |  600 +-
 fsl_dac.h                   |  714 +--
 fsl_dac32.c                 |  410 -
 fsl_dac32.h                 |  782 +--
 fsl_dmamux.c                |  182 
 fsl_dmamux.h                |  354 -
 fsl_dspi.c                  | 4484 +++++++++---------
 fsl_dspi.h                  | 2474 +++++-----
 fsl_dspi_edma.c             | 3060 ++++++------
 fsl_dspi_edma.h             |  592 +-
 fsl_edma.c                  | 5698 ++++++++++++------------
 fsl_edma.h                  | 1902 ++++----
 fsl_enc.c                   | 1186 ++---
 fsl_enc.h                   |  916 +--
 fsl_enet.c                  | 6778 ++++++++++++++--------------
 fsl_enet.h                  | 3710 +++++++--------
 fsl_ewm.c                   |  280 -
 fsl_ewm.h                   |  436 -
 fsl_flash.h                 |   82 
 fsl_flexbus.c               |  508 +-
 fsl_flexbus.h               |  486 +-
 fsl_flexcan.c               | 7128 +++++++++++++++---------------
 fsl_flexcan.h               | 2844 ++++++------
 fsl_flexcan_edma.c          |  478 +-
 fsl_flexcan_edma.h          |  280 -
 fsl_flexio.c                |  848 +--
 fsl_flexio.h                | 1400 ++---
 fsl_flexio_camera.c         |  430 -
 fsl_flexio_camera.h         |  460 -
 fsl_flexio_camera_edma.c    |  496 +-
 fsl_flexio_camera_edma.h    |  260 -
 fsl_flexio_i2c_master.c     | 2516 +++++-----
 fsl_flexio_i2c_master.h     |  972 ++--
 fsl_flexio_i2s.c            | 1806 +++----
 fsl_flexio_i2s.h            | 1120 ++--
 fsl_flexio_i2s_edma.c       |  894 +--
 fsl_flexio_i2s_edma.h       |  406 -
 fsl_flexio_spi.c            | 2652 +++++------
 fsl_flexio_spi.h            | 1404 ++---
 fsl_flexio_spi_edma.c       |  948 ++--
 fsl_flexio_spi_edma.h       |  414 -
 fsl_flexio_uart.c           | 1982 ++++----
 fsl_flexio_uart.h           | 1140 ++--
 fsl_flexio_uart_edma.c      |  814 +--
 fsl_flexio_uart_edma.h      |  356 -
 fsl_ftfx_adapter.h          |  786 +--
 fsl_ftfx_cache.c            | 1098 ++--
 fsl_ftfx_cache.h            |  248 -
 fsl_ftfx_controller.c       | 2888 ++++++------
 fsl_ftfx_controller.h       | 1644 +++---
 fsl_ftfx_features.h         |  180 
 fsl_ftfx_flash.c            | 2950 ++++++------
 fsl_ftfx_flash.h            | 1326 ++---
 fsl_ftfx_flexnvm.c          | 1012 ++--
 fsl_ftfx_flexnvm.h          | 1144 ++--
 fsl_ftfx_utilities.h        |  134 
 fsl_ftm.c                   | 2410 +++++-----
 fsl_ftm.h                   | 2054 ++++----
 fsl_gpio.c                  |  764 +--
 fsl_gpio.h                  | 1148 ++--
 fsl_hsadc.c                 | 2082 ++++----
 fsl_hsadc.h                 | 1266 ++---
 fsl_i2c.c                   | 4846 ++++++++++----------
 fsl_i2c.h                   | 1610 +++---
 fsl_i2c_edma.c              | 1234 ++---
 fsl_i2c_edma.h              |  240 -
 fsl_llwu.c                  |  962 ++--
 fsl_llwu.h                  |  652 +-
 fsl_lmem_cache.c            | 1498 +++---
 fsl_lmem_cache.h            |  930 +--
 fsl_lpi2c.c                 | 4630 +++++++++----------
 fsl_lpi2c.h                 | 2532 +++++-----
 fsl_lpi2c_edma.c            | 1036 ++--
 fsl_lpi2c_edma.h            |  314 -
 fsl_lpit.c                  |  368 -
 fsl_lpit.h                  |  752 +--
 fsl_lpspi.c                 | 4442 +++++++++---------
 fsl_lpspi.h                 | 2244 ++++-----
 fsl_lpspi_edma.c            | 2308 ++++-----
 fsl_lpspi_edma.h            |  602 +-
 fsl_lptmr.c                 |  346 -
 fsl_lptmr.h                 |  748 +--
 fsl_lpuart.c                | 4102 ++++++++---------
 fsl_lpuart.h                | 1724 +++----
 fsl_lpuart_edma.c           |  888 +--
 fsl_lpuart_edma.h           |  346 -
 fsl_ltc.c                   |10414 ++++++++++++++++++++++----------------------
 fsl_ltc.h                   | 3374 +++++++-------
 fsl_ltc_dpa.h               | 1994 ++++----
 fsl_ltc_edma.c              | 3338 +++++++-------
 fsl_ltc_edma.h              | 1668 +++----
 fsl_pdb.c                   |  326 -
 fsl_pdb.h                   | 1250 ++---
 fsl_pit.c                   |  292 -
 fsl_pit.h                   |  664 +-
 fsl_pmc.c                   |  240 -
 fsl_pmc.h                   |  852 +--
 fsl_port.h                  |  954 ++--
 fsl_pwm.c                   | 1870 +++----
 fsl_pwm.h                   | 1974 ++++----
 fsl_pwt.c                   |  266 -
 fsl_pwt.h                   |  588 +-
 fsl_qspi.c                  | 1158 ++--
 fsl_qspi.h                  | 1502 +++---
 fsl_qspi_edma.c             |  792 +--
 fsl_qspi_edma.h             |  324 -
 fsl_rcm.c                   |  138 
 fsl_rcm.h                   |  824 +--
 fsl_rnga.c                  |  640 +-
 fsl_rnga.h                  |  228 
 fsl_rtc.c                   | 1582 +++---
 fsl_rtc.h                   |  980 ++--
 fsl_sai.c                   | 7528 +++++++++++++++----------------
 fsl_sai.h                   | 3144 ++++++-------
 fsl_sai_edma.c              | 1414 ++---
 fsl_sai_edma.h              |  536 +-
 fsl_sdhc.c                  | 3224 ++++++-------
 fsl_sdhc.h                  | 2202 ++++-----
 fsl_sdramc.c                |  402 -
 fsl_sdramc.h                |  522 +-
 fsl_sim.c                   |  142 
 fsl_sim.h                   |  302 -
 fsl_smartcard.h             |  548 +-
 fsl_smartcard_emvsim.c      | 2286 ++++-----
 fsl_smartcard_emvsim.h      |  364 -
 fsl_smartcard_phy.h         |  254 -
 fsl_smartcard_phy_emvsim.c  |  454 -
 fsl_smartcard_phy_tda8035.c | 1122 ++--
 fsl_smc.c                   | 1034 ++--
 fsl_smc.h                   |  842 +--
 fsl_sysmpu.c                |  678 +-
 fsl_sysmpu.h                |  832 +--
 fsl_tpm.c                   | 1854 +++----
 fsl_tpm.h                   | 1344 ++---
 fsl_trgmux.c                |  118 
 fsl_trgmux.h                |  204 
 fsl_trng.c                  | 3870 ++++++++--------
 fsl_trng.h                  |  456 -
 fsl_tsi_v4.c                |  576 +-
 fsl_tsi_v4.h                | 1376 ++---
 fsl_uart.c                  | 3622 +++++++--------
 fsl_uart.h                  | 1624 +++---
 fsl_uart_edma.c             |  846 +--
 fsl_uart_edma.h             |  346 -
 fsl_vref.c                  |  584 +-
 fsl_vref.h                  |  466 -
 fsl_wdog.c                  |  480 +-
 fsl_wdog.h                  |  824 +--
 fsl_wdog32.c                |  282 -
 fsl_wdog32.h                |  796 +--
 fsl_xbara.c                 |  458 -
 fsl_xbara.h                 |  366 -
 fsl_xbarb.c                 |  252 -
 fsl_xbarb.h                 |  164 
 172 files changed, 115698 insertions(+), 115698 deletions(-)
[galak@spiff hal_nxp]$ 
```

**Comment by galak** [comment]
> > I did run dos2unix on the files. Do you see anything that I may have missed?
> 
> I just ran it on `dos2unix mcux/drivers/kinetis/*` and get:

Looks like whatever you pushed just now fixed it.

**Comment by mmahadevan108** [comment]
> > > I did run dos2unix on the files. Do you see anything that I may have missed?
> > 
> > 
> > I just ran it on `dos2unix mcux/drivers/kinetis/*` and get:
> 
> Looks like whatever you pushed just now fixed it.

Thanks. I had missed running dos2unix on one folder

**Comment by hakehuang** [comment]
@mmahadevan108 let me trigger a full test on this new sdk and compare with all v2.4.0 result, this may takes few days

**Comment by mmahadevan108** [comment]
Thank you @hakehuang

**Comment by mmahadevan108** [comment]
> @mmahadevan108 let me trigger a full test on this new sdk and compare with all v2.4.0 result, this may takes few days

**Comment by hakehuang** [comment]
@mmahadevan108 , I do a full round of all SDk tests, there is no issues found in this SDK hal level change

**Comment by mmahadevan108** [comment]
@hakehuang Thank you. You will need the below PR for zephyr changes:
https://github.com/zephyrproject-rtos/zephyr/pull/27990

**Comment by MaureenHelm** [comment]
cc: @jhqian

**Comment by hakehuang** [comment]
> @hakehuang Thank you. You will need the below PR for zephyr changes:
> [zephyrproject-rtos/zephyr#27990](https://github.com/zephyrproject-rtos/zephyr/pull/27990)

@mmahadevan108 thanks, now it is ok.

**Comment by mmahadevan108** [comment]
Anything else needed for this?

**Comment by mmahadevan108** [comment]
Are there any comments?

**Comment by hakehuang** [comment]
@mmahadevan108 , sorry, when double check the detailed test log, I find there are many issues in enet application

```
[ 50%] Building C object zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_mcux.c.obj

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_tx':

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:744:11: error: too few arguments to function 'ENET_SendFrame'

  744 |  status = ENET_SendFrame(context->base, &context->enet_handle,

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1427:10: note: declared here

 1427 | status_t ENET_SendFrame(ENET_Type *base,

      |          ^~~~~~~~~~~~~~

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_rx':

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:788:11: error: too few arguments to function 'ENET_GetRxFrameSize'

  788 |  status = ENET_GetRxFrameSize(&context->enet_handle,

      |           ^~~~~~~~~~~~~~~~~~~

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1362:10: note: declared here

 1362 | status_t ENET_GetRxFrameSize(enet_handle_t *handle, uint32_t *length, uint8_t ringId);

      |          ^~~~~~~~~~~~~~~~~~~

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:795:3: error: too few arguments to function 'ENET_GetRxErrBeforeReadFrame'

  795 |   ENET_GetRxErrBeforeReadFrame(&context->enet_handle,

      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1325:6: note: declared here

 1325 | void ENET_GetRxErrBeforeReadFrame(enet_handle_t *handle, enet_data_error_stats_t *eErrorStatic, uint8_t ringId);

      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:817:11: error: too few arguments to function 'ENET_ReadFrame'

  817 |  status = ENET_ReadFrame(context->base, &context->enet_handle,

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1405:10: note: declared here

 1405 | status_t ENET_ReadFrame(

      |          ^~~~~~~~~~~~~~

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:884:11: error: too few arguments to function 'ENET_ReadFrame'

  884 |  status = ENET_ReadFrame(context->base, &context->enet_handle, NULL, 0);

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1405:10: note: declared here

 1405 | status_t ENET_ReadFrame(

      |          ^~~~~~~~~~~~~~

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_mcux_init':

/build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:1088:42: warning: passing argument 2 of 'ENET_SetCallback' from incompatible pointer type [-Wincompatible-pointer-types]

 1088 |  ENET_SetCallback(&context->enet_handle, eth_callback, context);

      |                                          ^~~~~~~~~~~~

      |                                          |

      |                                          void (*)(ENET_Type *, enet_handle_t *, enet_event_t,  void *) {aka void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  void *)}

In file included from /build/src/workspace/frdm_k64f_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/frdm_k64f_socket_master/modules/hal/nxp/mcux/drivers/kinetis/./fsl_enet.h:1302:62: note: expected 'enet_callback_t' {aka 'void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  struct enet_frame_info *, void *)'} but argument is of type 'void (*)(ENET_Type *, enet_handle_t *, enet_event_t,  void *)' {aka 'void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  void *)'}

 1302 | void ENET_SetCallback(enet_handle_t *handle, enet_callback_t callback, void *userData);

      |                                              ~~~~~~~~~~~~~~~~^~~~~~~~

make[2]: *** [zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_mcux.c.obj] Error 1

zephyr/CMakeFiles/zephyr.dir/build.make:502: recipe for target 'zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_mcux.c.obj' failed

make[1]: *** [zephyr/CMakeFiles/zephyr.dir/all] Error 2

CMakeFiles/Makefile2:2828: recipe for target 'zephyr/CMakeFiles/zephyr.dir/all' failed

Makefile:102: recipe for target 'all' failed

make: *** [all] Error 2

script returned exit code 2
```

**Comment by hakehuang** [comment]
and many issues on t series boards

```
zephyr/CMakeFiles/zephyr.dir/build.make:445: recipe for target 'zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_mcux.c.obj' failed

CMakeFiles/Makefile2:2809: recipe for target 'zephyr/CMakeFiles/zephyr.dir/all' failed

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_tx':

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:744:11: error: too few arguments to function 'ENET_SendFrame'

  744 |  status = ENET_SendFrame(context->base, &context->enet_handle,

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1427:10: note: declared here

 1427 | status_t ENET_SendFrame(ENET_Type *base,

      |          ^~~~~~~~~~~~~~

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_rx':

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:788:11: error: too few arguments to function 'ENET_GetRxFrameSize'

  788 |  status = ENET_GetRxFrameSize(&context->enet_handle,

      |           ^~~~~~~~~~~~~~~~~~~

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1362:10: note: declared here

 1362 | status_t ENET_GetRxFrameSize(enet_handle_t *handle, uint32_t *length, uint8_t ringId);

      |          ^~~~~~~~~~~~~~~~~~~

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:795:3: error: too few arguments to function 'ENET_GetRxErrBeforeReadFrame'

  795 |   ENET_GetRxErrBeforeReadFrame(&context->enet_handle,

      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1325:6: note: declared here

 1325 | void ENET_GetRxErrBeforeReadFrame(enet_handle_t *handle, enet_data_error_stats_t *eErrorStatic, uint8_t ringId);

      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:817:11: error: too few arguments to function 'ENET_ReadFrame'

  817 |  status = ENET_ReadFrame(context->base, &context->enet_handle,

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1405:10: note: declared here

 1405 | status_t ENET_ReadFrame(

      |          ^~~~~~~~~~~~~~

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:884:11: error: too few arguments to function 'ENET_ReadFrame'

  884 |  status = ENET_ReadFrame(context->base, &context->enet_handle, NULL, 0);

      |           ^~~~~~~~~~~~~~

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1405:10: note: declared here

 1405 | status_t ENET_ReadFrame(

      |          ^~~~~~~~~~~~~~

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c: In function 'eth_mcux_init':

/build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:1088:42: warning: passing argument 2 of 'ENET_SetCallback' from incompatible pointer type [-Wincompatible-pointer-types]

 1088 |  ENET_SetCallback(&context->enet_handle, eth_callback, context);

      |                                          ^~~~~~~~~~~~

      |                                          |

      |                                          void (*)(ENET_Type *, enet_handle_t *, enet_event_t,  void *) {aka void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  void *)}

In file included from /build/src/workspace/mimxrt1050_evk_socket_master/zephyr/drivers/ethernet/eth_mcux.c:39:

/build/src/workspace/mimxrt1050_evk_socket_master/modules/hal/nxp/mcux/drivers/imx/./fsl_enet.h:1302:62: note: expected 'enet_callback_t' {aka 'void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  struct enet_frame_info *, void *)'} but argument is of type 'void (*)(ENET_Type *, enet_handle_t *, enet_event_t,  void *)' {aka 'void (*)(struct <anonymous> *, struct _enet_handle *, enum _enet_event,  void *)'}

 1302 | void ENET_SetCallback(enet_handle_t *handle, enet_callback_t callback, void *userData);

      |                                              ~~~~~~~~~~~~~~~~^~~~~~~~

make[2]: *** [zephyr/CMakeFiles/zephyr.dir/drivers/ethernet/eth_mcux.c.obj] Error 1

make[1]: *** [zephyr/CMakeFiles/zephyr.dir/all] Error 2

make: *** [all] Error 2

Makefile:102: recipe for target 'all' failed

script returned exit code 2
```

**Review by MaureenHelm — COMMENTED** [review]
Looks good. Will you please also update `mcux/README`?

**Comment by mmahadevan108** [comment]
> Looks good. Will you please also update `mcux/README`?

Thank you. I have updated this file

**Review by galak — APPROVED** [review]

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
