### PR TITLE
FRDM_KL46Z MCUX 5 hal header and basic files added.

### PR DESCRIPTION
**Pull request by mdecandia81**
Signed-off-by: Michele Jr De Candia <mdecandia@gmail.com>

### CODE REVIEW

**Comment by mdecandia81** [comment]
No, I didn't see it was there. I will reimport the SDK through import_mcux_sdk.py.

Thanks.

**Comment by galak** [comment]
Hmm, this version of the SDK that you imported with licensed Clear-BSD which historically hasn't been acceptable to the project.  I'm guessing there's an older SDK version that's just plain BSD.

Also, I'm guessing that the KL46Z SDK hasn't been updated in a while, so we need to be careful with the driver updates.

@MaureenHelm any thoughts?

**Comment by galak** [comment]
Will really need a PR on the Zephyr SDK that adds a basic SoC/Board port to test this change.

See https://docs.zephyrproject.org/latest/guides/modules.html#process on how to link the PRs for testing purposes.

**Comment by mdecandia81** [comment]
> Hmm, this version of the SDK that you imported with licensed Clear-BSD which historically hasn't been acceptable to the project. I'm guessing there's an older SDK version that's just plain BSD.
> 
> Also, I'm guessing that the KL46Z SDK hasn't been updated in a while, so we need to be careful with the driver updates.
> 
> @MaureenHelm any thoughts?

how to get older SDKs?

**Comment by mdecandia81** [comment]
> Will really need a PR on the Zephyr SDK that adds a basic SoC/Board port to test this change.
> 
> See https://docs.zephyrproject.org/latest/guides/modules.html#process on how to link the PRs for testing purposes.

Made pull request on zephyr https://github.com/zephyrproject-rtos/zephyr/pull/20752 to test changes and add support for the board.

**Pull request closed without merging**
