### PR TITLE
dts: nxp: kinetis: add pinctrl for ke17z

### PR DESCRIPTION
**Pull request by ankeXiao**
Added pinctrl files for ke17z7

### CODE REVIEW

**Comment by ankeXiao** [comment]
Hi @dleach02 @EmilioCBen @hakehuang @decsny @mmahadevan108 @DerekSnell @yvanderv , it's strange that I can't add reviewers manually, please help me review, thanks!

**Comment by hakehuang** [comment]
> Hi @dleach02 @EmilioCBen @hakehuang @decsny @mmahadevan108 @DerekSnell @yvanderv , it's strange that I can't add reviewers manually, please help me review, thanks!

can you create a pr for ke17z in zephyr so that I can trigger an integration build/run test. @ankeXiao

**Comment by ankeXiao** [comment]
> > Hi @dleach02 @EmilioCBen @hakehuang @decsny @mmahadevan108 @DerekSnell @yvanderv , it's strange that I can't add reviewers manually, please help me review, thanks!
> 
> can you create a pr for ke17z in zephyr so that I can trigger an integration build/run test. @ankeXiao

Please review zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/72439

**Review by danieldegrasse — APPROVED** [review]

**Comment by danieldegrasse** [comment]
We should wait to merge this until https://github.com/zephyrproject-rtos/zephyr/pull/72439 has gone through review and is ready to merge, just to avoid potential dependency issues

**Comment by decsny** [comment]
> We should wait to merge this until [zephyrproject-rtos/zephyr#72439](https://github.com/zephyrproject-rtos/zephyr/pull/72439) has gone through review and is ready to merge, just to avoid potential dependency issues

how could there be a dependency issue? these are new header files specific to the platform

**Pull request merged**
