### PR TITLE
mcux-sdk-middleware-usb: remove duplicate files

### PR DESCRIPTION
**Pull request by jsiverskog**
these files just cause confusion.

### CODE REVIEW

**Comment by jsiverskog** [comment]
corresponding zephyr pr: https://github.com/zephyrproject-rtos/zephyr/pull/67490

**Comment by jsiverskog** [comment]
@danieldegrasse : do you have time to review this? thanks

**Comment by danieldegrasse** [comment]
@mmahadevan108 could you take a look at this? It looks like these files are duplicates of https://github.com/zephyrproject-rtos/hal_nxp/blob/master/mcux/middleware/mcux-sdk-middleware-usb/device/usb_device.h.

@jsiverskog I appreciate the cleanup- could you make a corresponding PR to https://github.com/nxp-mcuxpresso/mcux-sdk? I would like to avoid carrying a patch removing these files if possible, since we import the MCUX SDK from that repository.

**Comment by jsiverskog** [comment]
@danieldegrasse : upstream PR merged!

**Review by danieldegrasse — APPROVED** [review]

**Comment by jsiverskog** [comment]
@danieldegrasse should i close https://github.com/zephyrproject-rtos/zephyr/pull/67490 ? it's not important to get that one merged, we can wait for https://github.com/zephyrproject-rtos/zephyr/pull/67483 instead

**Pull request merged**
