### PR TITLE
Upstream harpoon v2.4

### PR DESCRIPTION
**Pull request by JiafeiPan**
The patches in this PR is from Harpoon v2.4, and Susan has already pushed them to https://github.com/nxp-mcuxpresso/mcux-sdk/commits/main, so port them to hal_nxp.

### CODE REVIEW

**Comment by jahedul-haque** [comment]
Please add a License File to the repo

**Comment by JiafeiPan** [comment]
> Please add a License File to the repo

May I know do you mean license file for hal_nxp? if yes, I think it is not in this PR scope, maybe need to check with the maintainer @dleach02 , thanks.

**Comment by DerekSnell** [comment]
> Please add a License File to the repo

Hi @jahedul-haque ,
Thank you for raising this. We created a new issue https://github.com/zephyrproject-rtos/zephyr/issues/61514 to track this, and NXP will be updating the HAL soon with a license file.

**Review by mmahadevan108 — COMMENTED** [review]
Have these changes been sent to the mcux-sdk github repo?

**Comment by mmahadevan108** [comment]
@JiafeiPan We are in the process of updating to SDK release 2.14. I think we should be getting this change as part of that update. Please confirm.

**Comment by JiafeiPan** [comment]
> @JiafeiPan We are in the process of updating to SDK release 2.14. I think we should be getting this change as part of that update. Please confirm.

Yes, I can decline this PR if you can get this changes as part of v2.14 update, thanks.

**Comment by mmahadevan108** [comment]
@JiafeiPan . The SDK 2.14 update PR has been merged. Kindly close this PR if this is no longer required.

**Comment by JiafeiPan** [comment]
> @JiafeiPan . The SDK 2.14 update PR has been merged. Kindly close this PR if this is no longer required.

Sure, thanks.

**Pull request closed without merging**
