### PR TITLE
Update usb middleware

### PR DESCRIPTION
**Pull request by mmahadevan108**
This changes the middleware SDK USB code to use what is available in github repo.
https://github.com/NXPmicro/mcux-sdk-middleware-usb

This also deletes the "middleware/usb" folder. All local changes have been removed so that we can use the SDK USB driver without any local changes needed for Zephyr.

Update the build system to use the new USB middleware from github.

### CODE REVIEW

**Comment by mmahadevan108** [comment]
cc @decsny @EmilioCBen @yvanderv

**Comment by hakehuang** [comment]
@mmahadevan108  I will run a test with this change, will feedback next week

**Comment by mmahadevan108** [comment]
You will see failures on RT platforms as we are waiting for these 2 PR's to get merged: 
https://github.com/zephyrproject-rtos/zephyr/pull/49368
https://github.com/zephyrproject-rtos/zephyr/pull/49435

LPC, RT5xx, RT6xx should pass.

**Comment by hakehuang** [comment]
@mmahadevan108 , I meet issue with rt685 see below log, command line

scripts/twister -p mimxrt685_evk_cm33 -T tests/subsys/usb/ --build-only
```
ERROR   - mimxrt685_evk_cm33        tests/subsys/usb/bos/usb.bos                       FAILED: Build failure
ERROR   - see: /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/mimxrt685_evk_cm33/tests/subsys/usb/bos/usb.bos/build.log
INFO    - Total complete:    2/   4  50%  skipped:    1, failed:    0
ERROR   - mimxrt685_evk_cm33        tests/subsys/usb/device/usb.device                 FAILED: Build failure
ERROR   - see: /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/mimxrt685_evk_cm33/tests/subsys/usb/device/usb.device/build.log
INFO    - Total complete:    3/   4  75%  skipped:    1, failed:    0
ERROR   - mimxrt685_evk_cm33        tests/subsys/usb/desc_sections/usb.desc_sections   FAILED: Build failure
ERROR   - see: /home/shared/disk/zephyr_project/zephyr_test/zephyr/twister-out/mimxrt685_evk_cm33/tests/subsys/usb/desc_sections/usb.desc_sections/build.log
INFO    - Total complete:    4/   4  100%  skipped:    1, failed:    0
INFO    - 0 of 4 test configurations passed (0.00%), 3 failed, 1 skipped with 0 warnings in 11.31 seconds
INFO    - 0 test configurations executed on platforms, 3 test configurations were only built.
INFO    - Saving reports...

```

**Comment by hakehuang** [comment]
same issue with 
lpcxpresso55s69_cpu0
frdm_k22f
frdm_k64f
frdm_k82f
lpcxpresso55s69_cpu0

**Comment by mmahadevan108** [comment]
Please use the code from Zephyr PR https://github.com/zephyrproject-rtos/zephyr/pull/49497

**Comment by hakehuang** [comment]
@mmahadevan108 thanks, with this PR #49497 all above platfrom test pass.

**Comment by mmahadevan108** [comment]
@hakehuang, I have rebased PR #49497 so that tests on RT series should now pass. Can you please confirm.

**Comment by hakehuang** [comment]
> @hakehuang, I have rebased PR #49497 so that tests on RT series should now pass. Can you please confirm.

@mmahadevan108 I rebase the code, not the RT series test OK

**Comment by mmahadevan108** [comment]
> > @hakehuang, I have rebased PR #49497 so that tests on RT series should now pass. Can you please confirm.
> 
> @mmahadevan108 I rebase the code, not the RT11xx, RT10xx and RT5xx, RT6xx series test OK

Hi Hake, Can you please confirm if all tests are passing. If so, can you please approve

**Review by hakehuang — APPROVED** [review]
Test PASS on baord farm RT/Kinetis/LPC platform

**Review by danieldegrasse — APPROVED** [review]

**Pull request merged**
