### PR TITLE
mcux: add device and driver files for K8x series SoCs

### PR DESCRIPTION
**Pull request by fbrozovic**
Add mcux 2.6.0 device and driver files for NXP Kinetis K8x series
SoCs (MK80F25615 and MK82F25615). Update several drivers that were
already imported for other SoCs but also apply to K8x.

Origins: NXP MCUxpresso SDK 2.6.0
URL: mcuxpresso.nxp.com
Maintained-by: External

Signed-off-by: Filip Brozovic <fbrozovic@gmail.com>

### CODE REVIEW

**Comment by fbrozovic** [comment]
ping @MaureenHelm 

Would be nice to have this merged by 2.1 (along with support for KV5x and its eval board).

**Comment by galak** [comment]
> ping @MaureenHelm
> 
> Would be nice to have this merged by 2.1 (along with support for KV5x and its eval board).

While not suggesting to hold this up, but wonder about updating the hal across the board to 2.6

**Comment by MaureenHelm** [comment]
> > Would be nice to have this merged by 2.1 (along with support for KV5x and its eval board).

Agreed
 
> While not suggesting to hold this up, but wonder about updating the hal across the board to 2.6

I plan do to that right after we finish the zephyr 2.0 release.

**Comment by galak** [comment]
@fbrozovic do you want to look at updating this now that @MaureenHelm has done the 2.6.0 import for the existing HALs.

**Comment by galak** [comment]
looks the file perms on fsl_sim.{c,h}, fsl_tpm.h are changed.

**Comment by fbrozovic** [comment]
@galak @MaureenHelm rebased onto master, fixed file perms - hope this is OK now.

I will wait for this (and zephyrproject-rtos/zephyr#18527) to be merged so I can rebase #3 on top of it.

**Pull request merged**
